### ISSUE TITLE
embedded comma in double quoted string causes failures

### ISSUE THREAD

**Issue by VintageGeek** [jokedst/CsvQuery#10]
![image](https://user-images.githubusercontent.com/2395168/35115145-0bf8a9e4-fc3c-11e7-8f2c-33a94194f8a1.png)

Using this example:
"ControlID","Status","FeatureName","ResourceGroupName","ResourceName","ChildResourceName","ControlSeverity","IsBaselineControl","SupportsAutoFix","Description","Recommendation","DetailedLogFile"
"test123","test123","test123","test123","test123","test123","test123","test123","test123","test123","comma goes here, ","test123"

I get the error above.  It doesn't prompt to manually parse, but if i manually parse with default settings, file is read correctly. 

v1.2.5

Thanks!

**Comment by jokedst** [comment]
Thank's for the bug report.
It seems the analyzer decides that the best separator is double quotes, not comma... (all rows has the same number of quotes, but not two rows has the same number of quotes).

I could make a quick fix to avoid quotes (which would make the manual settings pop up instead).
Long term quoted string analysis will be added

**Comment by VintageGeek** [comment]
Ah, understood.  I'll make the change on my local repo and wait for your longer term fix
