### ISSUE TITLE
Error when trying to open NPP w/ CSVQuery plugin

### ISSUE THREAD

**Issue by mvieira2** [jokedst/CsvQuery#11]
I have tried NPP 7.5.1 and 7.5.4, both threw the same error.

When I try opening NPP I get this error message. I tried installing by dropping the CSVQuery.dll into the plugins folder and also tried via the plugins manager. I tried the newest test version and 1.2.5 and 1.2.0 versions of CSVQuery.

CSV Query Error
Error configuring the SQLite database ':memory:': Method not found: '!!0[] System.Array.Empty()'. Falling back to in-memory SQLite

After this message I get a popup from NPP saying that CsvQuery.dll is not compatible with the current version of Notepad++.

**Comment by jokedst** [comment]
That sounds like a pre-.NET 4.6 error...
Wheat version of .NET do you have? Windows update should install at least 4.7, and CsvQuery 1.2.0 used .NET 4.6.1. 
(CsvQuery 1.2.5 requires .NET 4.7.1 which has been part of windows update since Jan 9)

**Comment by mvieira2** [comment]
Looks like my work PC has 4.5.51209... :| I know other people in the office that can use CSVQuery no problem...

**Comment by mvieira2** [comment]
Thanks for pointed me in the right direction. Framework update fixed the problem!!
