### ISSUE TITLE
Package isnt trusted by Notepad++ Plugin Manager.

### ISSUE THREAD

**Issue by sboulianne** [jokedst/CsvQuery#15]
Hi,
I can install the plugin but I saw an warning that the plugin is not trusted bu Notepad++ plugin manager.
Is it possible to trust it please ?

Thanks.

**Comment by sboulianne** [comment]
I use Notepad++ x64.

[cid:image001.png@01D432E7.91169F00]

Sébastien Boulianne
Administrateur réseau & système / Network & System Administrator (Linux, Solaris & Windows).
Gestion des infrastructures / Infrastructure Management.
CCNA / CompTIA Server+ / MCSA Server 2016 / Spécialiste en supervision.
sebastien.boulianne@cpu.ca<mailto:sebastien.boulianne@cpu.ca>

[cid:image002.jpg@01D432E7.91169F00]


2323, du Versant Nord, suite 100
Québec (Québec) G1N 4P4
Téléphone : (418) 681 6974 poste 666
Ligne sans frais : 1 888 681 6974
Télécopieur : (418) 681 1444


Partenaire affilié Telus Santé

[cid:image005.jpg@01D432E7.911E4020]
Information confidentielle : Le présent message, ainsi que tout fichier qui y est joint, est envoyé à l'intention exclusive de son ou de ses destinataires, il est de nature confidentielle et peut constituer une information privilégiée. Nous avertissons toute personne autre que le destinataire prévu que tout examen, réacheminement, impression, copie, distribution ou autre utilisation de ce message et de tout fichier qui y est joint est strictement interdit. Si vous n'êtes pas le destinataire prévu, veuillez en aviser immédiatement l'expéditeur par retour de courriel et supprimer ce message et tout document joint de votre système. Merci.

Confidentiality Warning : This message and any attachments are intended only for the use of the intended recipient(s), are confidential, and may be privileged. If you are not the intended recipient, you are hereby notified that any review, retransmission, conversion to hard copy, copying, circulation or other use of this message and any attachments is strictly prohibited. If you are not the intended recipient, please notify the sender immediately by return e-mail, and delete this message and any attachments from your system. Thank you.

« Gérer c’est prévoir (voir avant, avoir une vision de l’avenir) »
[cid:image004.jpg@01D432E7.91169F00]

De : jokedst [mailto:notifications@github.com]
Envoyé : 13 août 2018 09:21
À : jokedst/CsvQuery <CsvQuery@noreply.github.com>
Cc : Sebastien Boulianne <Sebastien.Boulianne@cpu.ca>; Author <author@noreply.github.com>
Objet : Re: [jokedst/CsvQuery] Package isnt trusted by Notepad++ Plugin Manager. (#15)


Where did it say that?
Are you using 32-bit or 64-bit Notepad++?

It "works for me", but as a developer my setup is a bit unorthodox...

**Comment by jokedst** [comment]
Really odd... I have no idea, the hash is correct.
But I've released 1.2.6. and pushed that to PluginManager, hopefully that one get's trusted. But it will probably take a few days before PM is updated

**Comment by jokedst** [comment]
Seeing how the plugin manager has been replaced by a build in one, this isssue is obselete
