### ISSUE TITLE
Error configuring the SQLite database

### ISSUE THREAD

**Issue by intuitionfly** [jokedst/CsvQuery#16]
![image](https://user-images.githubusercontent.com/12625881/44252272-38351b80-a22e-11e8-843d-2f7ed36bb837.png)

After plugin installation, and open notepad++, this dialog pop up. I guess a library is missing or version mismatch. Is there any advise? Any help would be much appreciated. Thanks.

Platform: Win 7 x64
Notepad++ version: 7.5.8 x64
Plugin release version: 1.2.6 x64

**Comment by jokedst** [comment]
That sounds like the ame problem reported in #11 - your installed .NET library is too old.

Run windows update. It should install the latest .NET library for you.

**Comment by intuitionfly** [comment]
It's resolved after .Net framework upgrade to 4.7.2. Thanks for your help.
