### ISSUE TITLE
Add support for horizontal scroll

### ISSUE THREAD

**Issue by zhangfeiran** [jokedst/CsvQuery#18]
By saying horizontal scroll, I mean wheel left/right or shift+wheel up/down
Thanks~

**Comment by jokedst** [comment]
I did a quick attempt at this, but for some reason the (windows) grid control has no support for that, and side scrolling is not a standard event, meaning I'd have to hook into the windows message queue directly... 

No humongous deal, but more complex than a one-liner

**Comment by zhangfeiran** [comment]
I just accidentally found that ctrl+wheel up/down can (partially) achieve this goal: it just jumps from left side to right side in one roll if I use mouse; but under touchpad (with two finger up&down + ctrl) it will stay in middle, though not as smooth as expect, but I'm satisfied enough :)
