### ISSUE TITLE
How do I stipulate tab separator in Manual Parse Settings?

### ISSUE THREAD

**Issue by FarrelBuch** [jokedst/CsvQuery#21]
I have a TSV file where the headers are on the 5th line of the text file. The plugin is not parsing correctly. I thought I could help by stipulating that the separator was not a comma. I tried typing the tab key but that just pushes me to "Quote inside text prefix". I tried Alt9 or Alt0009 (I am on Windows 10). Nothing worked. Can you help me?

Love what your plugin does.

**Comment by jokedst** [comment]
Write \t

**Comment by FarrelBuch** [comment]
Ah yes. Never thought of that. There are a few non-printing symbols such as that.` \n` is for newline. There are a few escape sequences in programming languages (eg [Python](https://docs.python.org/2.0/ref/strings.html), R)

**Comment by FarrelBuch** [comment]
It worked well. Thank you.
