### ISSUE TITLE
multiple file tabs for query joins?

### ISSUE THREAD

**Issue by glowworms** [jokedst/CsvQuery#23]
Hi, is it possible to do joins against other files or file tabs?

eg.

SELECT *
FROM Customer.csv
INNER JOIN Orders.csv
ON Customer.csv.ID = Orders.csv.ID

I know this is getting a little complex but it would be a nice feature.

**Comment by jokedst** [comment]
Yes, it's possible. But the table names aren't that intuitive...
The first file you parse becomes table T1. The second T2 and so on. (the
alias "THIS" is always the file you're currenty viewing)

So you can write

SELECT *
FROM T1
INNER JOIN T2
ON T1.ID = T2.ID
