### ISSUE TITLE
Add "Show Column Number" & "Show Column Excel Letter"

### ISSUE THREAD

**Issue by EvoWebFrance** [jokedst/CsvQuery#26]
Hello,

This module is wonderfull !

Just some features missing for me, add two new entries in right-click popup menu :
"Show Column Number" starting from "0" (I'm a coder)
"Show Column Excel Letters"

Perhaps add in settings panel :
- start row count from 0 or 1 (with 1 per default to keep version compatibility)
- start column count from 0 or 1

Thank you and sorry for my bad english.

**Comment by jokedst** [comment]
The row numbers are something I don't think I can control, it's part of the windows built-in "grid" control. I just turn it on or off. It would be a major rewrite to make it into a column where I can control what is actually shown...

As for showing columns "Excel style" I'm curious what the use case could be? 
I mean if you absolutely need it you could just edit the first line in the file to "A,B,C,D,E,..." before clicking "Read file"
