### ISSUE TITLE
Invisible icon in toolbar when using new fluent icon style (npp v8 onwards)

### ISSUE THREAD

**Issue by puffpppp** [jokedst/CsvQuery#28]
Using Default Style:
![image](https://user-images.githubusercontent.com/35478508/121769183-cddc8b00-cb7f-11eb-8dda-babc8cde757f.png)
Using new style:
![image](https://user-images.githubusercontent.com/35478508/121769201-e5b40f00-cb7f-11eb-9812-f64e9a03d34e.png)

Saw below comment on the [compare plugin page](https://github.com/pnedev/compare-plugin/issues/261):
> specifically, plugin authors need to call NPPM_ADDTOOLBARICON_FORDARKMODE instead of NPPM_ADDTOOLBARICON if Notepad++ v8.0 or newer. (Actually, I don't think it hurts to call both, to keep the plugin compatible with older versions...)

**Comment by jokedst** [comment]
Wow. Thanks for the bug report (been on vacation so didn't see it until now).
Kinda bad by Npp to break all plugin icons out there... But I'll try to make a fix.

**Comment by jokedst** [comment]
Ok, seems like Npp got the hint from other users, there is a fix that will allow old plugins to at least show their old icons in dark mode: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/302bab894fd421fde371e04247357bc45728d729

It will be in next release I guess.

However, the CsvQuery icon still looks like crap in dark mode. You can't see the "CQ", it just looks like some sort of crosshair.. :P
So I'll still have to fix this, but it's not as urgent.

**Comment by jokedst** [comment]
This is now fixed, and v1.2.8 has been published and merged to the plugin admin list
