### ISSUE TITLE
feature request: add option to not reset the sql query on action "Read file"

### ISSUE THREAD

**Issue by jeroenwalter** [jokedst/CsvQuery#29]
My use case is that I often need to reload a file or load a new file with the same kind of contents. 
I need to use the same sql query on these files.
When I press "Read File", the sql query is reset to "SELECT * FROM THIS"
And I have to set it back to the query I need to use.
I would like an option that disables the reset of the query, either via an option in the Settings dialog, or via a checkbox next to the "Read File" button.

**Comment by jokedst** [comment]
That makes sense. If you just refresh a file that's already loaded, it should just re-run the same query.
I'll see what I can do.
