### ISSUE TITLE
ROW_NUMBER not supported

### ISSUE THREAD

**Issue by redcloud80** [jokedst/CsvQuery#31]
Hi! Is the ROW_NUMBER function actually supported? Any alternatives? Thanks!

**Comment by jokedst** [comment]
The version of SQLite included in CsvQuery does not support window functions, and never will.
There are workarounds, like this one: https://stackoverflow.com/questions/16847574/how-to-use-row-number-in-sqlite

If you absolutely MUST have this, you can use SQL Server as backend instead. You need SQL Server installed locally (there are free versions). Perhaps I should write something about how to set that up on the main page...

But basically you need SQL Server installed (with integrated security enabled, but that's he default).
Create an empty DB in SQL Server, e.g. "CsvQueryDB"
Go to N++ -> Plugins -> CsvQuery -> Settings
Set "StorageProvider" to MSSQL
Set "Database" to "CsvQueryDB"
Now click "Read File" again, and it will become a table in that database, and you can use SQL Server syntax in CsvQuery, including ROW_NUMBER.
