### ISSUE TITLE
feature request: Saving file settings 

### ISSUE THREAD

**Issue by trdm** [jokedst/CsvQuery#32]
Saving file settings. 
or for files with a specific extension, let's say * .txtsqlite 
Many times called the team: "Плаги&ны->CsvQuery->Manual parse settings"
And many times mistaken: (

Сохранение настроек дла файла
или для файлов с определенным расширением, допустим *.txtsqlite
Много раз вызывал команду "Плаги&ны->CsvQuery->Manual parse settings"
И много раз ошибался :(

**Comment by jokedst** [comment]
If I understand you correctly, you want the parse settings to be saved, so it reuses the same settings when opening a similar file?
That's a good idea...

**Comment by trdm** [comment]
You did not answer for a long time, so I solved the problem a little friend.
https://github.com/trdm/sqlquery.
I placing CVS files in SQLite: Memory: database with settings from the file itself.

**Comment by jokedst** [comment]
Cool! Closing this then.
