### ISSUE TITLE
feature request: do query on more than one Notepad++ tab.

### ISSUE THREAD

**Issue by Luuk34** [jokedst/CsvQuery#37]
Suppose I have two opened CSV files, on tabs `New 1` and `New 2`.

It would be great when a query like this could work:

```
SELECT *
FROM "New 1" as n1
LEFT JOIN "New 2" as n2 on n2.i = n1.i
```

(provided, of course, that columns `i` do exist in both CSV's)

Things I can think of that needs attention:
1) The tablename `THIS` should be rename to that name of the current tab.
2) Care should be taken when the name of the tab changes (save as...)
3) ...... ?

**Comment by jokedst** [comment]
You can do this already!
The tables are called "T1", "T2" etc.
To see what tables exists, you can type "SELECT * FROM sqlite_master".
This query is available in the plugin menu, "Plugins" -> "CsvQuery" -> "List parsed files"

**Comment by teotwawki42** [comment]
It seems that I was able to do table joins on prior versions, but joining T1 and T2 I now receive an error.
Upon running SELECT * FROM T1 LEFT JOIN T1.FROM = T2.FFL I receive the following error.
---------------------------
CSV Query Error
---------------------------
Could not execute query:
near "FROM": syntax error
---------------------------
OK   
---------------------------

**Comment by jokedst** [comment]
You need an "ON" in there.
i.e. "SELECT * FROM T1 LEFT JOIN T2 ON T1.FROM = T2.FFL"

**Comment by Luuk34** [comment]
Thanks!, I must have overlooked that option. This is making this plugin even better... 😉
