### ISSUE TITLE
CSVQuery not working on Notepad++ 8.4.8

### ISSUE THREAD

**Issue by paulsimongb** [jokedst/CsvQuery#39]
Hi

CSVQuery 1.2.9 is not working on Notepad++ 8.4.8. When I select Toggle CSV Query Window, nothing happens. There is no error but the split screen parsing into columns no longer happens.

**Comment by paulsimongb** [comment]
These are the Plug Ins installed in case the problem is due to a conflict between them, however, for example CSV Query used to work Ok with CSV lint.

![image](https://user-images.githubusercontent.com/26175830/210400386-66069dbc-9c25-4313-9b9b-4450e5ce286c.png)

**Comment by jokedst** [comment]
Can not reproduce :(
Works for me. I tried both 64 bit and 32 bit Notepad++, I installed CSV Lint and it worked fine with both running on the same file.

Could you try to turn on "debug mode" in the settings, then select "manual parse settings" in the CSV Query menu, then click "Try again". A debug popup should show some statistics. Does it? If CSV query crashes or something that debug window shouldn't show up.

**Comment by freeriderx11** [comment]
Hello

I have this error on Notpad++ 8.4.8 when I clic Read File in CSVQuery :
![2023-01-05_09h49_01](https://user-images.githubusercontent.com/122011537/210739726-4f69d01f-97b2-4698-ab01-361356850e51.png)

**Comment by paulsimongb** [comment]
Hi

I tried what you suggested.

The debug window does open and shows

![image](https://user-images.githubusercontent.com/26175830/210757795-7e8bcd5a-38b1-47ff-8f60-d988d1ccedbf.png)

I tried it with Manual Parse Settings as follows

![image](https://user-images.githubusercontent.com/26175830/210758420-55b65fe2-094c-4e65-9855-b547e10888cf.png)

and also with 

![image](https://user-images.githubusercontent.com/26175830/210758605-aa695ce6-f0b2-4f0d-83d7-648cedfc8fa6.png)

Neither work.

The overall Debug Info for Notepad++ is 


Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.2364
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    CSVLint (0.4.6.2)
    CsvQuery (1.2.9)
    mimeTools (2.9)
    nppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (2.0.3)
    XMLTools (3.1.1.13) 

Regards

Paul SImon

**Comment by jokedst** [comment]
That debug popup indicates CSVQuery "works", as in it parses and displays the results. Somewhere.

Could it be that you have detached the window and it's hiding outside the screen or something? I know that happened to me in the past :P Can't remember how I fixed it though.

@freeriderx11 that seems like an unrelated problem. That looks like some problem when writing the CSV to the data grid. Could you try another CSV file?

**Comment by paulsimongb** [comment]
Hi

I finally figured out what was going on. The window was docked in the lower pane and somehow, the lower pane had zero height so it was there but invisible. I just needed to drag the split point up.
