### ISSUE TITLE
CSV Query windows only appear when Notepad++ is run as Administrator

### ISSUE THREAD

**Issue by kupdegrove** [jokedst/CsvQuery#48]
I am running Notepad++ 8.6.4 x64 on Windows 10 Enterprise v21H2. The plugin version is 1.2.9.  Although some of the menu items seem to work (e.g. CvsQuery > Manual Parse Settings), when I select "Toggle CSV Query Window" nothing happens. When I run Notepad++ as Administrator, everything works flawlessly.

Unfortunately, this is a work computer and I do not have Admin rights. I was able to test with temporary Admin access but this is not something I can do going forward. Is there a way to set permissions so the plugin will run as a non-elevated user?

**Comment by jokedst** [comment]
That's really odd. It should not be like that. 
Try removing the addon and reinstall. Or reinstall the whole Notepad++. Something is wrong in your installation.

I just tried locally with a local windows account. No admin needed for the plugin to work.

**Comment by kupdegrove** [comment]
> That's really odd. It should not be like that. Try removing the addon and reinstall. Or reinstall the whole Notepad++. Something is wrong in your installation.
> 
> I just tried locally with a local windows account. No admin needed for the plugin to work.

Unfortunately, I've tried just reinstalling the addon which, didn't work so I tried completely uninstalling and reinstalling Notepad++ and the addon. Now I'm getting the attached error I was not getting before. I've confirmed running as Admistrator fixes it. I will not have this access for long. Is there a directory that requires permissions or something?
![csvQueryError](https://github.com/jokedst/CsvQuery/assets/86802564/dea66e7b-0c3b-4b5c-8bc7-b3ac7422e31b)

**Comment by jokedst** [comment]
The plugin is installed in `C:\Program Files\Notepad++\plugins\CsvQuery`, like all plugins. 
Or if you use 32 bit N++, `C:\Program Files (x86)\Notepad++\plugins\CsvQuery`
Perhaps take a look at the permissions there.

**Comment by kupdegrove** [comment]
Tried that as well. It only affects the lower fixed window that appears with certain plugins. I'm not a programmer but, I'm assuming there is a common library being called and somehow that only runs with elevated access

**Comment by jokedst** [comment]
Either way, glad you got it solved!
